parameters:
#    david_blog.example.class: David\BlogBundle\Example

services:
#    david_blog.example:
#        class: %david_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
